# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1821195fefb1a05cf5e64b0c2a29531ed4d1bebccd9e3a3a103fa1f25b8feabd6c7f0caec18bbcd025e2b71088242512fc62fac57eca804a3ac417952fdf398b

test:
  secret_key_base: 92b8d41f0f71262e1f0850b31ba1efe6fe72c8cac919f3acef2077c3ac3ea9107cee9f7d79ed8326dc15ff5e98eae5afdb6f5691b55ec51d551a21b3b08ab7b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
